### PR TITLE
Added new Card Issuer Mx

### PR DESCRIPTION
**Pull request by notsafety**
Added : 543921 of Mexico

### CODE REVIEW

**Comment by iannuttall** [comment]
Hey @ishlovenko thanks for the PR! Was it just the following line added?

> 543921,MASTERCARD,DEBIT,STANDARD,"INTELIGENCIA EN FINANZAS, S.A.P.I. DE C.V. ALBO",MX,MEX,Mexico,Mexico,,https://www.albo.mx,

I think I need a better way to organise the data, as one large CSV is a problem. If that's the only line, I may have to manually add it for now and then work on breaking the repo down into individual files based on BIN range instead.

**Comment by notsafety** [comment]
Is only 1 Added, but i will work to pull all the new i found to the project.
Only the line of
`543921,MASTERCARD,DEBIT,STANDARD,"INTELIGENCIA EN FINANZAS, S.A.P.I. DE C.V. ALBO",MX,MEX,Mexico,Mexico,,https://www.albo.mx,`
Was added

**Comment by iannuttall** [comment]
Awesome, thanks! I'll try and change the repo around so it's much easier to do PR's without a huge 40MB CSV

**Comment by notsafety** [comment]
Dont worry, will document that it was updated when i pull new updates.

~Love the project

**Comment by notsafety** [comment]
1 Row Updated With Correct Info

Deleted : 
476684,VISA,CREDIT,,MOSCOW MUNICIPAL BANK-BANK OF MOSCOW,US,USA,United States,United States,,,merged into VTB Bank

Added : 
476684,VISA,DEBIT,,"	BANCO NACIONAL DE MEXICO, S.A.",MX,Mexico,Mexico,Mexico,,www.banamex.com,

**Comment by notsafety** [comment]
Question, You sell the site of binlist.io script ?

**Review by iannuttall — APPROVED** [review]

**Pull request closed without merging**
