### PR TITLE
Cleanup of whitespaces

### PR DESCRIPTION
**Pull request by kierany5**
Possibly a fix to #11 although I haven't tested an imported into SQL Server and there is not much detail to go on.

This PR removes some unnecessary whitespaces from the data.  Completed by simply importing into a MySQL table, trimming all fields and exporting to CSV.

This fixes an issue with importing into the database via Ruby (which can be particularly sensitive to certain issues whereas other tools just ignore it):

```
CSV::MalformedCSVError: Unquoted fields do not allow \r or \n (line 343064).
from /usr/share/rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/csv.rb:1880:in `block (2 levels) in shift'
```

To cleanup I imported the data into a table:
```SQL
create table card_bins
(
    bin        int(10)      null,
    brand      varchar(255) null,
    type       varchar(255) null,
    category   varchar(255) null,
    issuer     varchar(255) null,
    alpha_2    varchar(255) null,
    alpha_3    varchar(255) null,
    country    varchar(255) null,
    latitude   varchar(255) null,
    longitude  varchar(255) null,
    bank_phone varchar(255) null,
    bank_url   varchar(255) null
);
```

Ran a very crude (possibly unnecessary) Update:
```SQL
UPDATE card_bins SET brand=TRIM(brand), type=TRIM(type), category=TRIM(category), issuer=TRIM(issuer), alpha_2=TRIM(alpha_2), alpha_3=TRIM(alpha_3), country=TRIM(country), latitude=TRIM(latitude), longitude=TRIM(longitude), bank_phone=TRIM(bank_phone), bank_url=TRIM(bank_url);
```

And then exported to back CSV.

I appreciate the time and effort put into this data set and I hope my contribution can be of help to others.

### CODE REVIEW

**Comment by kingthorin** [comment]
@kierany5 has this only been an issue as of the May 2020 updates?

@iannuttall perhaps you can update your scripts (python IIRC) to trim the fields as the CSV is being built?

**Comment by kierany5** [comment]
@kingthorin Yes, the recent updates are what caused the issues.  Ruby has a rather sensitive CSV reader that get's really touchy over these things.  My solution was just the quickest way of getting the format corrected with the tools open on my computer.

Thanks

**Comment by iannuttall** [comment]
I tested this in phpMyAdmin and it worked. Very hard to check all records obviously, but seems okay.

@kingthorin I'm not using any scripts really on this now. I used Python originally to scrape the data and then hired somebody to manually backfill a lot of bank information like website and phone numbers.

I've set up the latest version of the list on my own site: https://ian.is/binlist/

That site is on WordPress (I'm not a dev, so it's what I know best). If there is a way to automate merges into master to update that database table, I'd love that.

I could also use some help keeping this repo going by checking any additions to the list. I don't really have much time to dedicate to this and I don't use SQL a lot to know if the imports will work etc.

**Comment by kingthorin** [comment]
> That site is on WordPress (I'm not a dev, so it's what I know best). If there is a way to automate merges into master to update that database table, I'd love that.

That would be doable, if there's a way to initiate a remote connection to the DB (I can totally understand if there's not because that comes with it's own issues). You'd have to add the connection details here as secrets (so they're not exposed) and could then setup a GitHub action that runs on merge (or push) to perform the DB update from the file here.

> I could also use some help keeping this repo going by checking any additions to the list. I don't really have much time to dedicate to this and I don't use SQL a lot to know if the imports will work etc.

We could probably setup a kind of linter job that runs on PRs. Setup a temporary MySQL DB and try to import the file, fail the build if it can't be imported, pass it if it can. I could also look into existing CSV linters if there's such a thing 🤷

**Pull request merged**
